var searchData=
[
  ['general_20error_20codes',['General error codes',['../group__ble__err.html',1,'']]],
  ['generic_20access_20profile_20_28gap_29',['Generic Access Profile (GAP)',['../group__BLE__GAP.html',1,'']]],
  ['gap_20advertising_20and_20scan_20response_20data_20format',['GAP Advertising and Scan Response Data format',['../group__BLE__GAP__AD__TYPE__DEFINITIONS.html',1,'']]],
  ['gap_20address_20cycle_20modes',['GAP Address cycle modes',['../group__BLE__GAP__ADDR__CYCLE__MODES.html',1,'']]],
  ['gap_20address_20types',['GAP Address types',['../group__BLE__GAP__ADDR__TYPES.html',1,'']]],
  ['gap_20advertising_20filter_20policies',['GAP Advertising filter policies',['../group__BLE__GAP__ADV__FILTER__POLICIES.html',1,'']]],
  ['gap_20advertisement_20flags',['GAP Advertisement Flags',['../group__BLE__GAP__ADV__FLAGS.html',1,'']]],
  ['gap_20advertising_20interval_20max_20and_20min',['GAP Advertising interval max and min',['../group__BLE__GAP__ADV__INTERVALS.html',1,'']]],
  ['gap_20advertising_20timeout_20values',['GAP Advertising timeout values',['../group__BLE__GAP__ADV__TIMEOUT__VALUES.html',1,'']]],
  ['gap_20advertising_20types',['GAP Advertising types',['../group__BLE__GAP__ADV__TYPES.html',1,'']]],
  ['gap_20authentication_20key_20types',['GAP Authentication Key Types',['../group__BLE__GAP__AUTH__KEY__TYPES.html',1,'']]],
  ['gap_20attribute_20security_20requirement_20setters',['GAP attribute security requirement setters',['../group__BLE__GAP__CONN__SEC__MODE__SET__MACROS.html',1,'']]],
  ['gap_20connection_20parameters_20limits',['GAP Connection Parameters Limits',['../group__BLE__GAP__CP__LIMITS.html',1,'']]],
  ['gap_20discovery_20modes',['GAP Discovery modes',['../group__BLE__GAP__DISC__MODES.html',1,'']]],
  ['gap_20io_20capabilities',['GAP IO Capabilities',['../group__BLE__GAP__IO__CAPS.html',1,'']]],
  ['gap_20keypress_20notification_20types',['GAP Keypress Notification Types',['../group__BLE__GAP__KP__NOT__TYPES.html',1,'']]],
  ['gap_20roles',['GAP Roles',['../group__BLE__GAP__ROLES.html',1,'']]],
  ['gap_20scan_20interval_20max_20and_20min',['GAP Scan interval max and min',['../group__BLE__GAP__SCAN__INTERVALS.html',1,'']]],
  ['gap_20scan_20timeout_20max_20and_20min',['GAP Scan timeout max and min',['../group__BLE__GAP__SCAN__TIMEOUT.html',1,'']]],
  ['gap_20scan_20window_20max_20and_20min',['GAP Scan window max and min',['../group__BLE__GAP__SCAN__WINDOW.html',1,'']]],
  ['gap_20security_20status',['GAP Security status',['../group__BLE__GAP__SEC__STATUS.html',1,'']]],
  ['gap_20security_20status_20sources',['GAP Security status sources',['../group__BLE__GAP__SEC__STATUS__SOURCES.html',1,'']]],
  ['gap_20timeout_20sources',['GAP Timeout sources',['../group__BLE__GAP__TIMEOUT__SOURCES.html',1,'']]],
  ['generic_20attribute_20profile_20_28gatt_29_20common',['Generic Attribute Profile (GATT) Common',['../group__BLE__GATT.html',1,'']]],
  ['gatt_20bluetooth_20namespaces',['GATT Bluetooth Namespaces',['../group__BLE__GATT__CPF__NAMESPACES.html',1,'']]],
  ['gatt_20execute_20write_20flags',['GATT Execute Write flags',['../group__BLE__GATT__EXEC__WRITE__FLAGS.html',1,'']]],
  ['gatt_20handle_20value_20operations',['GATT Handle Value operations',['../group__BLE__GATT__HVX__TYPES.html',1,'']]],
  ['gatt_20status_20codes',['GATT Status Codes',['../group__BLE__GATT__STATUS__CODES.html',1,'']]],
  ['gatt_20timeout_20sources',['GATT Timeout sources',['../group__BLE__GATT__TIMEOUT__SOURCES.html',1,'']]],
  ['gatt_20write_20operations',['GATT Write operations',['../group__BLE__GATT__WRITE__OPS.html',1,'']]],
  ['generic_20attribute_20profile_20_28gatt_29_20client',['Generic Attribute Profile (GATT) Client',['../group__BLE__GATTC.html',1,'']]],
  ['generic_20attribute_20profile_20_28gatt_29_20server',['Generic Attribute Profile (GATT) Server',['../group__BLE__GATTS.html',1,'']]],
  ['gatt_20server_20attribute_20types',['GATT Server Attribute Types',['../group__BLE__GATTS__ATTR__TYPES.html',1,'']]],
  ['gatt_20server_20authorization_20types',['GATT Server Authorization Types',['../group__BLE__GATTS__AUTHORIZE__TYPES.html',1,'']]],
  ['gatt_20server_20operations',['GATT Server Operations',['../group__BLE__GATTS__OPS.html',1,'']]],
  ['gatt_20server_20service_20types',['GATT Server Service Types',['../group__BLE__GATTS__SRVC__TYPES.html',1,'']]],
  ['gatt_20value_20locations',['GATT Value Locations',['../group__BLE__GATTS__VLOCS.html',1,'']]],
  ['gap_5fenable_5fparams',['gap_enable_params',['../structble__enable__params__t.html#ac14566b7abd979db7845a24bf6b11ee4',1,'ble_enable_params_t']]],
  ['gap_5fevt',['gap_evt',['../structble__evt__t.html#a67ca1f9db570d1c2f196c0a316151af5',1,'ble_evt_t']]],
  ['gap_5fopt',['gap_opt',['../unionble__opt__t.html#a389cdb4378d2a7f989807dcf27145051',1,'ble_opt_t']]],
  ['gap_20security_20modes',['GAP Security Modes',['../group__GAP__SEC__MODES.html',1,'']]],
  ['gatt_5fmtu_5fsize_5fdefault',['GATT_MTU_SIZE_DEFAULT',['../group__BLE__GATT__DEFINES.html#gaf0a71c5d9dd3b12235312bd40fd2175e',1,'ble_gatt.h']]],
  ['gatt_5frx_5fmtu',['GATT_RX_MTU',['../group__BLE__GATT__DEFINES.html#ga69b579663f889c0ce87a8931b51048b4',1,'ble_gatt.h']]],
  ['gatt_5fstatus',['gatt_status',['../structble__gattc__evt__t.html#a844b25b255a6a17284b6285baa1fec6f',1,'ble_gattc_evt_t::gatt_status()'],['../structble__gatts__authorize__params__t.html#a22732489c5283481acd5d8c883dd6819',1,'ble_gatts_authorize_params_t::gatt_status()']]],
  ['gattc_5fevt',['gattc_evt',['../structble__evt__t.html#a2bdcb3c197239b4e5957d89bb0f26161',1,'ble_evt_t']]],
  ['gatts_5fenable_5fparams',['gatts_enable_params',['../structble__enable__params__t.html#ad2de18bc975930cadc754c5e3468c870',1,'ble_enable_params_t']]],
  ['gatts_5fevt',['gatts_evt',['../structble__evt__t.html#aea997556a147ad5541998f13699e27c1',1,'ble_evt_t']]],
  ['gpio_5fpin',['gpio_pin',['../structble__pa__lna__cfg__t.html#a98588797b646a5b41102e6b1deb9c8b4',1,'ble_pa_lna_cfg_t']]],
  ['gpiote_5fch_5fid',['gpiote_ch_id',['../structble__common__opt__pa__lna__t.html#a2756839a926a4f2a6203cc2e2fb6b43c',1,'ble_common_opt_pa_lna_t']]]
];
