var searchData=
[
  ['structures',['Structures',['../group__BLE__COMMON__STRUCTURES.html',1,'']]],
  ['svc_20return_20values_20specific_20to_20gap',['SVC return values specific to GAP',['../group__BLE__ERRORS__GAP.html',1,'']]],
  ['svc_20return_20values_20specific_20to_20gattc',['SVC return values specific to GATTC',['../group__BLE__ERRORS__GATTC.html',1,'']]],
  ['svc_20return_20values_20specific_20to_20gatts',['SVC return values specific to GATTS',['../group__BLE__ERRORS__GATTS.html',1,'']]],
  ['svc_20return_20values_20specific_20to_20l2cap',['SVC return values specific to L2CAP',['../group__BLE__ERRORS__L2CAP.html',1,'']]],
  ['structures',['Structures',['../group__BLE__GAP__STRUCTURES.html',1,'']]],
  ['structures',['Structures',['../group__BLE__GATT__STRUCTURES.html',1,'']]],
  ['structures',['Structures',['../group__BLE__GATTC__STRUCTURES.html',1,'']]],
  ['structures',['Structures',['../group__BLE__GATTS__STRUCTURES.html',1,'']]],
  ['system_20attribute_20flags',['System Attribute Flags',['../group__BLE__GATTS__SYS__ATTR__FLAGS.html',1,'']]],
  ['structures',['Structures',['../group__BLE__L2CAP__STRUCTURES.html',1,'']]],
  ['structures',['Structures',['../group__BLE__TYPES__STRUCTURES.html',1,'']]],
  ['softdevice_20global_20error_20codes',['SoftDevice Global Error Codes',['../group__nrf__error.html',1,'']]],
  ['softdevice_20nvic_20api',['SoftDevice NVIC API',['../group__nrf__nvic__api.html',1,'']]],
  ['softdevice_20nvic_20public_20functions',['SoftDevice NVIC public functions',['../group__NRF__NVIC__FUNCTIONS.html',1,'']]],
  ['softdevice_20nvic_20internal_20functions',['SoftDevice NVIC internal functions',['../group__NRF__NVIC__INTERNAL__FUNCTIONS.html',1,'']]],
  ['softdevice_20nvic_20internal_20definitions',['SoftDevice NVIC internal definitions',['../group__NRF__NVIC__ISER__DEFINES.html',1,'']]],
  ['softdevice_20manager_20api',['SoftDevice Manager API',['../group__nrf__sdm__api.html',1,'']]],
  ['softdevice_20manager_20error_20codes',['SoftDevice Manager Error Codes',['../group__nrf__sdm__error.html',1,'']]],
  ['soc_20library_20api',['SoC Library API',['../group__nrf__soc__api.html',1,'']]],
  ['soc_20library_20error_20codes',['SoC Library Error Codes',['../group__nrf__soc__error.html',1,'']]],
  ['structures',['Structures',['../group__NRF__SOC__STRUCTURES.html',1,'']]]
];
